const mongoose = require('mongoose');
const Stripe = require('stripe');

const orderSchema = new mongoose.Schema({
  // Order ID generated by Stripe
  stripeId: {
    type: String,
    required: true,
  },
  // Customer email
  email: {
    type: String,
    required: true,
  },
  // Array of book objects that are being purchased
  books: {
    type: [
      {
        title: String,
        author: String,
        price: Number,
      },
    ],
    required: true,
  },
  // Amount charged for the order, in cents
  amount: {
    type: Number,
    required: true,
  },
  // Date and time the order was placed
  createdAt: {
    type: Date,
    required: true,
  },
});

const Order = mongoose.model('Order', orderSchema);

module.exports = Order;
